"""
Django settings for rdio_back project.

Generated by 'django-admin startproject' using Django 1.11.25.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=gr12hsjsge=i5zdo3=yz$k9b!u5kkoqq)uh0m40x%arw^*mba'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost', #test locales
    'api.rdio.inmac.work', #back
    'rdio.inmac.work', #front
    '179.49.71.2', #oficina lima para pruebas
    '127.0.0.1',
    '192.168.137.1'
]

# CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = [
    "http://192.168.137.1:8080",
    "http://localhost:8080", #COMENTAR ESTA LINEA EN PRODUCCION
    "https://rdio.inmac.work"
]

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'revproxy',
    'rdioapp',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rdio_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rdio_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# COUCH DB Config
# COUCHDB_SERVER = 'http://admin:1234@127.0.0.1:5984'
COUCHDB_SERVER = '127.0.0.1:5984'
COUCH_DB = 'rdio_test'
FULL_COUCHDB_SERVER = 'http://127.0.0.1:5984'
COUCH_SECRET = '08b3d44062a2b92bd79622ccdff72fdf'

# TOKEN CONFIG. Duration in hours
TOKEN_DURATION = 24

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL.strip("/"))

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',

    ]
}

from .local import *

HAPIQA_VIEWS = {
    "clima": "VIEW_EXT_RDIO_CLIMA",
    'cuadrilla': 'VIEW_EXT_RDIO_CUADRILLA',
    'persona': 'VIEW_EXT_RDIO_PERSONA',
    'partidas': 'VIEW_EXT_RDIO_PARTIDAS',
    'proyecto': 'VIEW_EXT_RDIO_PROYECTOS',
    'equipo': 'VIEW_EXT_RDIO_EQUIPO',
    'rubro': 'VIEW_EXT_RDIO_RUBRO',
    'locacion': 'VIEW_EXT_RDIO_LOCACION',
    'sector': 'VIEW_EXT_RDIO_SECTOR',
    'operativo': 'VIEW_EXT_RDIO_OPERATIVO',
    'pxe': 'VIEW_EXT_RDIO_PROYECTO_X_EQUIPO',
    'pxm': 'VIEW_EXT_RDIO_PROYECTO_X_MATERIAL',
    'pxp': 'VIEW_EXT_RDIO_PROYECTO_X_PERSONA',
}

REPORT_TEMPLATE = BASE_DIR + '/report_templates/basic_reportV1.xlsx'
